name: Create Preview Image

on:
  pull_request:
    branches: ['master']
  types: [opened, synchronize, reopened]

jobs:
  preview_image:
    name: Push preview image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
        ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push preview image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            BlackHatMagic/Agathos-Bot:pr-${{ github.event.pull_request.number }}